### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by UnknownEvil** [evolvio4all/evolvio4JavaScript#1]
# REPLACED: GO TO "Projects" and look at "TODO"

Comment any ideas and I'll add them, and tell me what you're working on so I can put your name next to the item, to let others know.

# Map
### Coloring
- [x] All ground will be green, orange/red/yellow, or white depending on the season.
### Plants
- [ ] Trees (?)
- [x] Grass (ground?)
- [ ] Can also evolve(?)

### Features
- [ ] Toggle show smell areas (hover for info?)

&nbsp;

# Brain
### Inputs
- [x] Touch
- [ ] Sight (Info about creature it sees?)
- [ ] Smell
- [ ] Taste(?) 
- [ ] Sound
- [x] Age
- [x] Size
- [ ] Preferences
- [ ] Hunger
- [ ] Thirst
- [ ] Exhaustion

### Outputs
- [ ] Rotate
- [x] Move (Forward OR any angle?)
- [x] Eat (Non-Linear)
- [ ] Drink
- [ ] Noise
- [ ] Excrete (Waste Removal)
- [ ] Urinate (Smell)
- [x] Arousal
- [ ] Sleep
- [x] Attack

&nbsp;

# Creatures
### Preferences
- [ ] Diet(?)

### Biology
- [x] Age (somehow) makes you die more easily. (Certain actions require more energy, like moving?)
- [ ] Leave scent (communicates the creatures statuses - age, species, wants to breed, etc.)
- [ ] Gender

### Genes
- [x] Birth Size
- [ ] Full Growth Size
- [ ] Puberty Age (Puberty Requires more food, but makes rapid growth and allows breeding afterwards)
- [ ] Puberty Growth (Amount to grow during puberty)
- [x] Color
- [x] Brain Structure (If dynamic)
- [x] Brain Values
- [ ] Feature Positions (Eyes, Legs?, Mouth?)
- [ ] Features
- [x] Mutability? (Could be global)

### Breeding
- [x] Random Mutations at birth (Not JUST the average like before)

### Species
- [x] Similar creatures will be part of the same species
- [ ] Only similar creatures can breed [Speciation] (?)

&nbsp;

# Misc
- [ ] Disease? (Evolves?)
- [ ] Consider adding momentum (creature can add to, and as such friction) with a max limit to prevent spasming.

&nbsp;

# User Interface
### Creature
- [ ] Compact, easier to understand brain.
- [ ] Show natural traits (color, children, etc.)

### Config
- [ ] Sliders to tweak the simulation (some before, some during)

**Comment by winnie334** [comment]
Could you please consider making a github page for this repository? Takes only 2 minutes and makes the game a lot more accessible.

Thanks a lot for maintaining such a fun repo! :)

**Comment by UnknownEvil** [comment]
@winnie334 I'll see what I can do — the guy who actually owns the account isn't me.

**Comment by winnie334** [comment]
@UnknownEvil Well, that's basically the same thing (other than the longer URL), so it's good for me! Thanks for the response :)

**Comment by UnknownEvil** [comment]
Yeah, sorry it took so long — I'm not super active on github... I have been working on this project though

**Comment by evolvio4all** [comment]
That's a cool idea, to begin with it looks like the javascript version would be the best project to show. Maybe later we could make the home page show all of the projects once we have something working. I haven't got too much time but can have a look at it.

**Comment by evolvio4all** [comment]
I've just gone through the process and the website is available but it's all black for me. I'm using a tablet so that might be why, to be fair the rawgit site is all black for me too.

**Comment by UnknownEvil** [comment]
@evolvio4all thanks, I've updated the README.md to show this.
